import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { spawn } from 'node:child_process';
import net from 'node:net';
import WebSocket from '/home/kuang/workspace/robot_station/node_modules/ws/index.js';

const repoDir = process.cwd();
const port = 18081;
const receiverPort = 19091;
const dataDir = mkdtempSync(`${tmpdir()}/robot-station-test-`);
const env = { ...process.env, PORT:String(port), DATA_DIR:dataDir, ADMIN_EMAIL:'admin@example.com', ADMIN_PASSWORD:'ChangeMe-123456', ROBOT_HOST:'127.0.0.1', ROBOT_PORT:String(receiverPort), ROBOT_TOKEN:'test-token', NODE_ENV:'test' };
let child;
let receiver;
async function waitForPort(targetPort) { for (let i=0;i<50;i++) { try { await new Promise((resolve,reject)=>{ const socket=net.createConnection({host:'127.0.0.1',port:targetPort},()=>{socket.destroy();resolve();}); socket.once('error',reject); }); return; } catch {} await new Promise(r=>setTimeout(r,100)); } throw new Error(`port ${targetPort} did not open`); }
async function waitForHealth() { for (let i=0;i<50;i++) { try { const response=await fetch(`http://127.0.0.1:${port}/healthz`); if(response.ok)return; } catch {} await new Promise(r=>setTimeout(r,100)); } throw new Error('server did not start'); }
async function login(email,password) { const response=await fetch(`http://127.0.0.1:${port}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})}); assert.equal(response.status,200); const body=await response.json(); return {cookie:response.headers.get('set-cookie').split(';')[0],body}; }
function openControl(cookie) { return new Promise((resolve,reject)=>{ const ws=new WebSocket(`ws://127.0.0.1:${port}/api/control`,{headers:{cookie}}); const timer=setTimeout(()=>reject(new Error('websocket ready timeout')),3000); ws.once('message',raw=>{clearTimeout(timer);resolve({ws,ready:JSON.parse(raw.toString())})}); ws.once('error',reject); }); }
function request(ws,message) { return new Promise((resolve,reject)=>{ const timer=setTimeout(()=>reject(new Error('ack timeout')),3000); const handler=raw=>{ const value=JSON.parse(raw.toString()); if(value.type==='ack' && value.id===message.id){clearTimeout(timer);ws.off('message',handler);resolve(value);} }; ws.on('message',handler); ws.send(JSON.stringify(message)); }); }

before(async()=>{ receiver=spawn('python3',['tools/print_robot_receiver.py','--host','127.0.0.1','--port',String(receiverPort),'--token','test-token'],{cwd:repoDir,stdio:'ignore'}); await waitForPort(receiverPort); child=spawn('node',['apps/server/dist/index.js'],{cwd:repoDir,env,stdio:'ignore'}); await waitForHealth(); });
after(()=>{ child?.kill('SIGTERM'); receiver?.kill('SIGTERM'); rmSync(dataDir,{recursive:true,force:true}); });

test('operator websocket owns a lease server-side and correlates acks',async()=>{ const admin=await login('admin@example.com','ChangeMe-123456'); const bridge=await fetch(`http://127.0.0.1:${port}/bridge.js`); assert.equal(bridge.status,200); const saved=await fetch(`http://127.0.0.1:${port}/api/robot/connections`,{method:'POST',headers:{'content-type':'application/json',cookie:admin.cookie},body:JSON.stringify({name:'Integration receiver',host:'127.0.0.1',port:receiverPort,token:'test-token'})}); assert.equal(saved.status,201); const savedBody=await saved.json(); assert.equal(savedBody.data.connection.hasToken,true); const selected=await fetch(`http://127.0.0.1:${port}/api/robot/connect`,{method:'POST',headers:{'content-type':'application/json',cookie:admin.cookie},body:JSON.stringify({profileId:savedBody.data.connection.id})}); assert.equal(selected.status,200); assert.equal((await selected.json()).data.connected,true); const reconnect=await fetch(`http://127.0.0.1:${port}/api/robot/reconnect`,{method:'POST',headers:{cookie:admin.cookie}}); assert.equal(reconnect.status,200); const control=await openControl(admin.cookie); assert.equal(control.ready.type,'ready'); assert.equal(control.ready.data.robot.connected,true); const noLease=await request(control.ws,{web_v:1,type:'intent',id:'no-lease',action:'base.jog',params:{}}); assert.equal(noLease.code,'LEASE_REQUIRED'); const invalid=await request(control.ws,{web_v:1,type:'intent',id:'invalid',action:'shell.exec',params:{}}); assert.equal(invalid.code,'INVALID_ARGUMENT'); const enabled=await request(control.ws,{web_v:1,type:'intent',id:'enable',action:'control.enable',params:{}}); assert.equal(enabled.code,'OK'); assert.equal(enabled.data.lease_id,undefined); const second=await openControl(admin.cookie); const busy=await request(second.ws,{web_v:1,type:'intent',id:'busy',action:'control.enable',params:{}}); assert.equal(busy.code,'CONTROL_BUSY'); second.ws.close(); const jog=await request(control.ws,{web_v:1,type:'intent',id:'jog',action:'base.jog',motion_id:'motion-1',params:{motion_id:'motion-1',linear_mps:.1,deadline_ms:Date.now()+300}}); assert.equal(jog.code,'OK'); assert.equal(jog.motion_id,'motion-1'); const stopped=await request(control.ws,{web_v:1,type:'intent',id:'stop',action:'motion.stop_all',params:{}}); assert.equal(stopped.code,'OK'); control.ws.close(); await new Promise(r=>setTimeout(r,120)); const statusAfterRefresh=await fetch(`http://127.0.0.1:${port}/api/robot/status`,{headers:{cookie:admin.cookie}}); assert.equal(statusAfterRefresh.status,200); assert.equal((await statusAfterRefresh.json()).data.connected,true); const afterClose=await openControl(admin.cookie); assert.equal(afterClose.ready.data.robot.connected,true); const reclaimed=await request(afterClose.ws,{web_v:1,type:'intent',id:'reclaim',action:'control.enable',params:{}}); assert.equal(reclaimed.code,'OK'); afterClose.ws.close(); });

test('viewer websocket is read-only',async()=>{ const admin=await login('admin@example.com','ChangeMe-123456'); const created=await fetch(`http://127.0.0.1:${port}/api/users`,{method:'POST',headers:{'content-type':'application/json',cookie:admin.cookie},body:JSON.stringify({email:'viewer@example.com',displayName:'Viewer',password:'Viewer-12345678',role:'viewer'})}); assert.equal(created.status,201); const selfDisable=await fetch(`http://127.0.0.1:${port}/api/users/1`,{method:'PATCH',headers:{'content-type':'application/json',cookie:admin.cookie},body:JSON.stringify({enabled:false})}); assert.equal(selfDisable.status,409); const viewer=await login('viewer@example.com','Viewer-12345678'); const control=await openControl(viewer.cookie); const denied=await request(control.ws,{web_v:1,type:'intent',id:'viewer-motion',action:'base.jog',params:{}}); assert.equal(denied.code,'FORBIDDEN'); control.ws.close(); });
